[project]
name = "mlops-mlflow-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagshub>=0.6.4",
    "mlflow>=3.8.1",
    "seaborn>=0.13.2",
]
